version: '2'
services:
  api:
    image: node:6
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - API_PORT=$API_PORT
    ports:
      - "$API_PORT:$API_PORT"
    links:
      - postgres:postgreshost
    command: ./node_modules/.bin/nodemon api.js

  postgres:
    image: sameersbn/postgresql:9.4-13
    ports:
      - "5432:5432"
    environment:
      - DB_USER=$PG_USER
      - DB_PASS=$PG_PASS
      - DB_NAME=$PG_DBNAME
    volumes:
      - dbdata:/var/lib/postgresql

volumes:
  dbdata: {}
