version: '2'
services:
  api:
    image: node:6
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "$API_PORT:$API_PORT"
    links:
      - postgres:$API_PG_HOST
    command: ./node_modules/.bin/nodemon api.js

  postgres:
    image: sameersbn/postgresql:9.4-13
    ports:
      - "5432:5432"
    environment:
      - DB_USER=$PGUSER
      - DB_PASS=$PGPASSWORD
      - DB_NAME=$PGDATABASE
    volumes:
      - dbdata:/var/lib/postgresql

volumes:
  dbdata: {}
