version: '2'
services:
  api:
    image: node:6
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - API_PORT=9001
    ports:
      - "9001:9001"
    command: ./node_modules/.bin/nodemon api.js
