version: '2'
services:
  api:
    image: node:6
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - API_PORT=$API_PORT
    ports:
      - "$API_PORT:$API_PORT"
    command: ./node_modules/.bin/nodemon api.js
